### ISSUE TITLE
Uncaught TypeError when using atom-ide-crystal

### ISSUE THREAD

**Issue by peterschols** [crystal-lang-tools/atom-ide-crystal#23]
When saving a .cr file to invoke atom-ide-crystal, we receive the following error.

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: 'crystal' package vundefined

### Stack Trace

Uncaught TypeError: Bad argument

```
At /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:392

TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:321:63)
    at BufferedProcess.start (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:127:20)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:112:18)
    at format (/packages/crystal/lib/util/formatter.js:28:9)
    at /packages/crystal/lib/util/formatter.js:19:4
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1222:31
```

### Commands

```
  3x -7:04.0 editor:newline (input.hidden-input)
     -6:49.1.0 core:save (input.hidden-input)
     -6:40 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:12.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
autocomplete-ruby 0.2.8 
busy-signal 1.4.3 
ide-crystal 0.2.3 
intentions 1.1.5 
language-crystal-actual 0.36.0 
linter 2.2.0 
linter-js-standard 3.9.3 
linter-ruby 1.2.5 
linter-ui-default 1.6.5 
nucleus-dark-ui 0.12.3 
phantom-ui 1.0.0 
pretty-json 1.6.4 
rails-snippets 2.16.0 
ruby-block 0.3.6 
seti-ui 1.9.0 
spacegray-tomorrowdark-ui 2.1.0 
tail 0.1.0 
twilight-updated-syntax 0.5.5 
```

**Comment by konovod** [comment]
I have a same problem. https://gist.github.com/konovod/fa9ef858fbc1e249f4e31f492ccbe27a

**Comment by peterschols** [comment]
Any updates on this issue? Thanks!

**Comment by ddgromit** [comment]
The issue is the plugin settings are saved under `ide-crystal`, but the plugin is looking under `crystal`.  See [compiler.js](https://github.com/crystal-lang-tools/atom-ide-crystal/blob/master/lib/util/compiler.js#L14)

For a temporary fix, open the atom config and rename the `crystal-ide` key to `crystal`:

```cson
"*":
  crystal:
    compilerExecPath: "/usr/local/bin/crystal"
    formatOnSave: true
```

**Comment by ddgromit** [comment]
Submitted a PR with a fix: https://github.com/crystal-lang-tools/atom-ide-crystal/pull/26

**Comment by keplersj** [comment]
Moved to a [`scry`](https://github.com/crystal-lang-tools/scry) based implementation. No longer relevant.
